name: foreground_demo_pjo
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_local_notifications: any
  flutter_foreground_task: ^9.2.0
  http: ^1.1.0
  flutter_blue_plus: ^1.35.5
  permission_handler: ^12.0.1

  health_plugin:         # 名稱要跟插件資料夾裡的 pubspec.yaml 一致
    path: ./plugins/health_plugin  # 確保路徑指向你建立的資料夾

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# ✅ 保持原本的樣子,不要加 plugin 宣告
flutter:
  uses-material-design: true